### GET attributes
GET http://127.0.0.1:8000/attribute/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIxMTg2MjksInN1YiI6IjI0In0.J8UKPD-tw-edzfHIMrX8VdqvjZX69qTT5sWHaYvoU-0

### GET attribute
GET http://127.0.0.1:8000/attribute/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIxMTg2MjksInN1YiI6IjI0In0.J8UKPD-tw-edzfHIMrX8VdqvjZX69qTT5sWHaYvoU-0

### POST attribute
POST http://127.0.0.1:8000/attribute
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIxMTg2MjksInN1YiI6IjI0In0.J8UKPD-tw-edzfHIMrX8VdqvjZX69qTT5sWHaYvoU-0
Content-Type: application/json

{
    "title": "Weight"
}

### PATCH attribute
PATCH http://127.0.0.1:8000/attribute/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIxMTg2MjksInN1YiI6IjI0In0.J8UKPD-tw-edzfHIMrX8VdqvjZX69qTT5sWHaYvoU-0
Content-Type: application/json

{
    "title": "Weight 2"
}

### DELETE attribute

DELETE http://127.0.0.1:8000/attribute/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIxMTg2MjksInN1YiI6IjI0In0.J8UKPD-tw-edzfHIMrX8VdqvjZX69qTT5sWHaYvoU-0