### GET categories
GET http://127.0.0.1:8000/api/v1/categories/

### GET category
GET http://127.0.0.1:8000/api/v1/categories/19

### POST category
POST http://127.0.0.1:8000/api/v1/categories
Content-Type: application/json

{
    "title": "Fruits",
    "description": "Fruits category",
    "order": 200
}

### PATCH category
PATCH http://127.0.0.1:8000/api/v1/categories/22
Content-Type: application/json

{
    "title": "Fruits 2",
    "description": "Fruits category 2",
    "order": 2000
}

### DELETE category

DELETE http://127.0.0.1:8000/api/v1/categories/22