### GET products
GET http://127.0.0.1:8000/api/v1/products/

### GET product
GET http://127.0.0.1:8000/api/v1/products/22

### POST product
POST http://127.0.0.1:8000/api/v1/products
Content-Type: application/json

{
    "title": "Apple pie",
    "description": "Big apple pie"
}

### PATCH product
PATCH http://127.0.0.1:8000/api/v1/products/23
Content-Type: application/json

{
    "title": "Apple pie 2",
    "description": "Big apple pie 2"
}

### DELETE product

DELETE http://127.0.0.1:8000/api/v1/products/23