### GET users
GET http://127.0.0.1:8000/user/

### GET user
GET http://127.0.0.1:8000/user/15

### POST user
POST http://127.0.0.1:8000/user
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john3@doe.com",
    "password": "s3cr3tAndLong",
    "role": "user"
}

### PATCH user
PATCH http://127.0.0.1:8000/user/20
Content-Type: application/json

{
    "first_name": "Johnny2",
    "last_name": "Doe",
    "email": "john1@doe.com",
    "password": "s3cr3tAndLong",
    "role": "user"
}

### DELETE user

DELETE http://127.0.0.1:8000/user/18